### ISSUE TITLE
Dashboard. Improve transaction previews

### ISSUE THREAD

**Issue by OlegMakarenko** [symbol/desktop-wallet#1090]
1. Display amount only for native mosaic
2. Show mosaic icon for non-native mosaic transfers
3. Show envelope icon if message included
4. Display custom aggregate types (ex. Mosaic Creation -> [Mosaic Definition, Mosaic Supply Change])

Mobile wallet as example
![image](https://user-images.githubusercontent.com/33131259/107587323-320b3480-6c0a-11eb-95a2-2cd8640cad1e.png)

**Comment by cryptoBeliever** [comment]
@OlegMakarenko I think this issue https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/856 can be also improved here.

**Comment by myxmaster** [comment]
I agree that the current display is not good. A tx with multiple mosaics looks exactly like a tx with one mosaic in the dashboard.

I suggest the following:
- If a tx only contains XYM, display the amount followed by "XYM"
- If a tx contains no XYM but one non-native mosaic, display the amount followed by the mosaic icon.
- If a tx contains no XYM but multiple non-native mosaics, just display an icon indicating there a multiple mosaics. Example: ![grafik](https://user-images.githubusercontent.com/77545287/111906836-80ea8c00-8a4a-11eb-8d13-b6da7a7902c7.png)
- If a tx contains XYM and one or more non-native mosaics, display the XYM amount followed by "XYM" and the mosaic+ icon

**Comment by cryptoBeliever** [comment]
@bassemmagdy what should be changed in this issue?

**Comment by cryptoBeliever** [comment]
transaction 1:
- 2 mosaics (without symbol.xym)
transaction 2:
- without mosaics at all. with message
transaction 3:
- with mosaics (2XYM, 1 702AFE86F22BEEAF, 3 7C0E12FB21F32D9A)

- I don't see mosaics icon. BUG
- if there is no XYM should we present amount as other mosaic amount? BUG

![image](https://user-images.githubusercontent.com/17684281/121564910-390d4c80-ca1c-11eb-9ec9-2bdd20c61cf8.png)

**Comment by cryptoBeliever** [comment]
@bassemmagdy one small problem with preview when the transaction is first one then layer is cut.

![image](https://user-images.githubusercontent.com/17684281/121802418-70f2da80-cc3c-11eb-8c61-8d7c8972aa65.png)

**Comment by cryptoBeliever** [comment]
@bassemmagdy 
1) on branch sprint fixes I don't see a mosaics icon.
2) is this issue fixed https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1090#issuecomment-860182758 ?

**Comment by OlegMakarenko** [comment]
@bassemmagdy
Can we use the same icons with the Mobile Wallet for the consistency? 

https://github.com/nemgrouplimited/symbol-mobile-wallet/blob/main/src/assets/icons/message.png

https://github.com/nemgrouplimited/symbol-mobile-wallet/blob/main/src/assets/icons/mosaics.png

**Comment by cryptoBeliever** [comment]
Works fine. Already merged into main. Closed.
