### ISSUE TITLE
Could add address next to alias in confirmation screen for clarity. 

### ISSUE THREAD

**Issue by jabo38** [symbol/desktop-wallet#1151]
**Is your feature request related to a problem? Please describe.**
No problem really, just a very small thing that could make the wallet nicer

**Describe the solution you'd like**
When I send a tx by alias, it could be nice to confirm the address in the confirmation screen, just in case I mistyped or something. 

**Describe alternatives you've considered**
I made a mockup below of how it could work. 

![image](https://user-images.githubusercontent.com/10395907/108125134-a9f3b780-706d-11eb-9f05-fbb776915185.png)

**Comment by cryptoBeliever** [comment]
Fixed in dev. Closed.
