### ISSUE TITLE
Account selection not showing all available accounts

### ISSUE THREAD

**Issue by kodty** [symbol/desktop-wallet#1345]
When the wallet contains some multisig accounts (co-signer + a couple other 1 of 1s), only the multisig related accounts show in the drop down account selecter in the top right of the dash board. To select a non multisig account, you have to go to the accounts page, select the address, and go back to home.

**Comment by cryptoBeliever** [comment]
@kodty is this still valid? I can see all accounts in the top right corner selector.

**Comment by cryptoBeliever** [comment]
Looks like I can't reproduce anymore.
