### ISSUE TITLE
Co-signatory of a (2 of 3) multisig account cannot sign an aggregate bonded tx (for creating a multi-level multisig)

### ISSUE THREAD

**Issue by fajarvm** [symbol/desktop-wallet#1350]
There is a possible issue in Symbol Desktop Wallet where a multisig enabled account cannot sign an aggregate bonded transaction to become a cosignatory of a multi-level multisig account. Now, I'm not sure if this is an issue in the core code or in the desktop client.

Background:
I'm trying to setup a harvesting node on AllNodes, and as part of the process, I have to sign an aggregate bonded transaction created by an account managed by AllNodes. According to the instruction of AllNodes, I should be able to sign this transaction in Symbol Desktop Client by:
1. Go to Home,
2. Click on the aggregate bonded transaction, a transaction details pop-up dialog will be shown,
3. In the transaction details pop-up dialog, click on the confirm button

The problem:
There's no "confirm" button. (See screenshot)
This transaction details is also shown for all of my cosignatory accounts; no confirmation button.

Expected behaviour:
* There should be a confirmation button as seen here: https://docs.symbolplatform.com/guides/aggregate/signing-announced-aggregate-bonded-transactions.html
* A (cosignatory of a) multisig account should be able to sign an aggregate bonded transaction.

Screenshots:
TX Hash in screenshot: [C770144F3EFCC5B82F69F9C7B5DD4555798387D7D4904C276109F4512DDECFA7](http://explorer.symbolblockchain.io/transactions/C770144F3EFCC5B82F69F9C7B5DD4555798387D7D4904C276109F4512DDECFA7)
If more information is needed, I'd be happy to share. 

<img width="1046" alt="Screenshot 2021-03-20 at 16 15 45" src="https://user-images.githubusercontent.com/3041538/111875286-470d7d00-8999-11eb-91e8-36f817adfc73.png">

**Comment by surekabpm** [comment]
@AdriaCarrera I created the Multi level multisig account and initiated teh aggregate transaction but i dont see any pop or any confirm button . can you please check 
Test01- TB4XBSGSRDNKJKR25PX5O4X5CYCD2H2QDP75AII  Test 01, 02 are multisig and 03,04 are seerate multi sig , also added 04 to first multisig )
Test02- TCLDX3DL6PUWX7FTXL7OLFVE6WVNZAOR7ILCHLQ
Test03- TDW3SS2GL3PD6CE7K6XN3VPUAQVJ6RBWQ4LCR7Q
Test04- TAW5VFRUDMXNLOVUJ7IRI4MKRJRDYBV7BYVR4HY

**Comment by surekabpm** [comment]
screenshots 
![image](https://user-images.githubusercontent.com/49143210/113877910-c347f300-97d6-11eb-8810-5a3095850376.png)
![image](https://user-images.githubusercontent.com/49143210/113877987-d35fd280-97d6-11eb-817f-ef12ad45dc82.png)
![image](https://user-images.githubusercontent.com/49143210/113878248-0f933300-97d7-11eb-8e7e-5a25b1ad1335.png)

**Comment by NikolaiB** [comment]
@bassemmagdy I still can reproduce it. I am taking one multisig account with 2co-signers (ch1, chm2), convert chm2 co-signer into multisig with 2 co-signors (ch3, ch4). Initiating transaction from ch1 and expect to receive aggregate transaction in ch3 and ch4, but unsuccessfully. 
Mnemonic: `obscure basic stamp regular cloth buddy kick youth silver grain tattoo common
crisp arrive intact spice uncle ability lab nerve empower lion happy tuna`
