### ISSUE TITLE
Use NetworkGenerationHash for network identifier

### ISSUE THREAD

**Issue by rg911** [symbol/desktop-wallet#1412]
Currently, the wallet uses NetworkType for identifying a network, I would be better to change to use genHash (as a unique hash) as a network identifier.

**Comment by coiki** [comment]
Team decided to wait for @bassemmagdy

**Comment by cryptoBeliever** [comment]
Closing since we will not support private networks at this moment.
- https://github.com/symbol/desktop-wallet/pull/1568
- https://github.com/symbol/desktop-wallet/issues/1412
