### ISSUE TITLE
No clear way to install the desktop wallet on Ubuntu in offline mode

### ISSUE THREAD

**Issue by jabo38** [symbol/desktop-wallet#1471]
Trying to install the wallet in offline mode with an Ubuntu USB  doesn't work. I get to the install message and then it hangs at 0%.

**Comment by cryptoBeliever** [comment]
@jabo38 I was able to install using command line:

sudo dpkg -i symbol-desktop-wallet-linux-amd64-1.0.3.deb

Double click indeed doesn't work but I think this is by design.

**Comment by jabo38** [comment]
I was definitely double clicking.  

I probably wouldn’t be the only one to run into this problem so I’m wondering if there is a way to help others? Maybe putting the instructions in a read.me file?

**Comment by cryptoBeliever** [comment]
I'm changing the last comment. I think the issue is because the computer is offline. And to install wallet it requires some dependencies (which can't be installed without internet connection). Please check https://github.com/symbol/desktop-wallet/issues/998.
