### ISSUE TITLE
Problem activating delegated harvesting where all keys aren't linked. 

### ISSUE THREAD

**Issue by jabo38** [symbol/desktop-wallet#1476]
Steps to reproduce. 

1) I fund an account. 
2) Age in funds for a day that are over 10,000 but under 50m. 
3) I go to harvesting to link keys and initiate transaction 
4) Play around with wallet and start harvesting on another account 
5) Come back to the first account and see the following message

![image](https://user-images.githubusercontent.com/10395907/116793446-c8762600-aa94-11eb-92ca-ff68faea1663.png)

The first problem is that harvesting was activated on this device (using a Ledger just a few minutes ago). 

The second problem is that seemingly not all the keys are linked? 

![image](https://user-images.githubusercontent.com/10395907/116793469-ea6fa880-aa94-11eb-828f-a066e12a593e.png)

Not sure if that is part of the problem or not, but after manually entering in the node I used last time into the node box, I'm then given the only option to unlink my keys and then to later relink them. 

![image](https://user-images.githubusercontent.com/10395907/116793507-1db23780-aa95-11eb-9607-6927d2100a6f.png)

Unlinking and relinking works.

**Comment by bassemmagdy** [comment]
@jabo38 would you provide proper steps to reproduce?

**Comment by jabo38** [comment]
I did pretty much write the steps to reproduce.

**Comment by bassemmagdy** [comment]
@jabo38 Did you activate your harvesting on a different account or is it the same account in a different profile?

**Comment by jabo38** [comment]
All the screen shots are for the same account in the same profile on the same computer and same desktop app.

**Comment by cryptoBeliever** [comment]
I can reproduce problem with saving keys in this way:
- go to harvesting page (for account that have > 10000 XYM and importance > 0)
- click "Link keys" (transaction will be sent)
- do some interruption, like: change node, logout. After transaction will be confirmed you will end up with not saved private keys.

**Comment by cryptoBeliever** [comment]
@AnthonyLaw not sure if it should be seperate issue or belongs to this one. But it's very similar (this time wrong node is selected instead missing keys). If it should be reported as seperated one please let me know.

Steps:
1. Create empty profile
2. Import account with balance for which we will start harvesting.
3.  Go to harvesting page (by default will be selected current node - X)
4. Switch harvesting node to Y
5. Start harvesting, before transaction will be confirmed switch to other profile and switch current node to Z
6. Wait for harvesting transaction confirmation
7. After confirmation done switch to harvesting view and selected node will be current node (Z) instead correct node (Y)

Expected result:
Harvesting node should be node Y

Video: https://share.getcloudapp.com/P8u9nAqv

**Comment by cryptoBeliever** [comment]
After latest fix seems all works now :+1: 
- harvesting for single account - starting
- harvesting for single account - change harvested node
- harvesting for multisig account - starting
- harvesting for multisig account - change harvested node
- choosing node for account that already harvesting (in other wallet)
- choosing node for account that already harvesting on node (node operator account)

**Comment by cryptoBeliever** [comment]
Checked in dev. Works fine :+1:
