### ISSUE TITLE
Lack of Russian translation 

### ISSUE THREAD

**Issue by klimgeran** [symbol/desktop-wallet#1478]
I would like to add Russian translation to Symbol Wallet. This would greatly simplify the work for Russian-speaking users.

P.S. The Symbol mobile wallet has support for the Russian language, and the main desktop Symbol wallet does not support the Russian language.

Let's fix this?

As I understand it, the right way is `symbol-desktop-wallet/src/language/en-US.json`

**Comment by bassemmagdy** [comment]
Hi @klimgeran yes, you're right. If you can consume this  `symbol-desktop-wallet/src/language/en-US.json` to create a proper Russian translation file that would be very helpful, and we can take it from there.

**Comment by cryptoBeliever** [comment]
There is already Russian translation added. Closing.
