### ISSUE TITLE
Aggegate bonded - Failure_Core_Future_Deadline

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1490]
Steps:

1. Change system clock +1h
2. Try to send aggregate bonded transaction (for example multisig)

Result: Announcing hash lock failes with error "Failure_Core_Future_Deadline":

![image](https://user-images.githubusercontent.com/17684281/118023327-b8482b80-b35d-11eb-843b-05500c6b784a.png)

Questions:

1) Why Hash lock transaction deadline is set to 6 hours? Hash lock is confirmed immediately. Why it has 6h instead of 2h like a normal transaction?

2) When the user operating system clock is ahead 1minute (or node clock 1minute behind) the user gets an error as above. I assume here that the max deadline for the hash lock is 6h but it seems correct assumption.

3) Wouldn't better to use node time (/node/time) instead of local user time?

**Comment by fboucquez** [comment]
A couple of notes:

6 hours hash lock deadline doesn't make sense, the user is not going to wait for 6 hours before the wallet announces the bonded transaction. 

https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/96b1678b5943b631299511d165d074f4a1219e35/src/services/TransactionCommand.ts#L173

It could be the default 2 hours or even less. 

48 hours bonded is the top limit, the network may reject when the local time is slightly desynchronized.  

Both 6 and 48 hours should be wallet configuration, not hardcoded. 

I've created a service in the SDK that offsets any error. The wallet could create and share the service each time the repo factory is created via stores. 

https://github.com/nemtech/symbol-sdk-typescript-javascript/pull/790

The wallet could use DeadlineService.createDeadlineUsingOffset.

**Comment by coiki** [comment]
@surekabpm seems like this task was automatically moved to the Issue Backlog after you reopened it. Can you confirm it needs to be reopened?

**Comment by surekabpm** [comment]
This one by mistake I closed it and later have to reopen

**Comment by cryptoBeliever** [comment]
This should be tested after code review.

**Comment by cryptoBeliever** [comment]
@bassemmagdy announcing transaction doesn't work:

![image](https://user-images.githubusercontent.com/17684281/123991408-fca19080-d9ca-11eb-9b5d-64f4b407caa7.png)

**Comment by bassemmagdy** [comment]
@cryptoBeliever please provide some steps to reproduce.

**Comment by NikolaiB** [comment]
@bassemmagdy Create multisig account with 2 co-signors and initiate transaction from multisig account.

**Comment by cryptoBeliever** [comment]
Previous error I'm not able reproduce but now I can see errors with Timestamp too far in the future after a few tries of sending:

https://share.getcloudapp.com/z8uOGz6m

**Comment by cryptoBeliever** [comment]
Still got occasionally errors like this:

![image](https://user-images.githubusercontent.com/17684281/124378906-58fafd80-dcb4-11eb-911e-0a4de69eb640.png)

Also, sdk is not released (alpha version used) so my suggestion is not to include in the next release.

**Comment by cryptoBeliever** [comment]
As we discussed on the daily meeting there will be a change regarding time synchronization with a node. To avoid frequently ask /time endpoint.

**Comment by cryptoBeliever** [comment]
https://github.com/symbol/symbol-sdk-typescript-javascript/blob/81f5397b6f2db1d1c3eea15d3e8a41b6b82ae31f/src/service/DeadlineService.ts#L64

Methods: `localTimeOffset` and `createDeadlineUsingOffset`

**Comment by cryptoBeliever** [comment]
All issues fixed :+1:

**Comment by cryptoBeliever** [comment]
@bassemmagdy please merge into dev.
