### ISSUE TITLE
Add validation for mosaic field

### ISSUE THREAD

**Issue by NikolaiB** [symbol/desktop-wallet#1530]
WTR:

1. Go to Home page
2. Initiate transaction with bigger amount that you have

Result: When the button Send clicked, I am able to see password form
Expected result: add notification for this field, something like `you don't have enough balance`

![image](https://user-images.githubusercontent.com/11311924/122017100-7d656780-cde3-11eb-8a3a-c48ff92ff79c.png)

**Comment by cryptoBeliever** [comment]
I prefer validation made by the network. When you try send to big amount you will receive error message that you have insufficient balance. 
Isn't this related with https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/758?

**Comment by cryptoBeliever** [comment]
Now when amount is above supply error message is presented. When user try send above balance error message is presented.
