### ISSUE TITLE
Mosaic creation issue. Mosaic supply is unclear

### ISSUE THREAD

**Issue by OlegMakarenko** [symbol/desktop-wallet#1561]
**Problem:**
At this moment, the wallet use absolute amount for mosaic supply change, but there is no info about it.
It might be unclear to the user what amount will be received.

**Solution:**
Add a dynamic text field to present relative amount which will be received
| | |
| ------------- | ------------- |
| Supply (absolute amount): | 120 000  |
| Divisibility:  | 2  |
| Result amount:  | 1 200.00  |

![image](https://user-images.githubusercontent.com/33131259/123456823-f63a9f80-d5eb-11eb-8259-87a2e98c1cd3.png)

**Comment by yilmazbahadir** [comment]
This is how it'll look like. @cryptoBeliever @OlegMakarenko 

Not 100% sure about the labels but using `Supply Units` for the absolute and `Supply Amount` for the relative felt right.

Will raise the PR soon if that's alright. (Open to any other suggestions though.)

![image](https://user-images.githubusercontent.com/6256269/130140652-b16e0fc1-4513-4f8f-bbad-1f6830d4b21b.png)

**Comment by cryptoBeliever** [comment]
Considering also view to change supply:

![image](https://user-images.githubusercontent.com/17684281/130142990-1b12acf8-a43e-46ac-91c8-19eb1d1c7426.png)

I would:
- change `Supply Amount` to `Supply`
- change `Supply Change Amount` to `Supply Change Units`

**Comment by yilmazbahadir** [comment]
Yeah, that could work (if we refer `Supply` as relative by default)

Can you also check if the `Current Supply` and `New Supply` fields are formatted correctly? In the image you shared should be showing 4 decimal places for relative (the divisibility is 4)

**Comment by cryptoBeliever** [comment]
@yilmazbahadir  you are right. On supply modification view new and current relative supply is presented always with 3 places after decimal point. Places after decimal point should be equal to divisibility

Example mosaic with divisibility 6

![image](https://user-images.githubusercontent.com/17684281/130146345-10378ce1-c017-428c-96d9-30a8ea41b2dd.png)

**Comment by cryptoBeliever** [comment]
Fixed in dev branch.
