### ISSUE TITLE
Failed to read "keys-whitelist.json" Error: Cannot find module './keys-whitelist.json'

### ISSUE THREAD

**Issue by fboucquez** [symbol/desktop-wallet#1572]
When building the wallet

**Comment by OlegMakarenko** [comment]
@fboucquez is the build failed or just a console error?

**Comment by cryptoBeliever** [comment]
I've checked, and it's not stopping me from starting an application. Maybe we should change it to message instead of error with a stack trace?

**Comment by cryptoBeliever** [comment]
The file is now added to the repository.
