### ISSUE TITLE
Transaction history issue. One transaction is displayed twice

### ISSUE THREAD

**Issue by OlegMakarenko** [symbol/desktop-wallet#1576]
The wallet displays the Aggregate Complete transaction twice. Transaction is confirmed but the second time it is shown as unconfirmed.
![image](https://user-images.githubusercontent.com/33131259/124293863-c3e6f000-db5f-11eb-8261-c87888344727.png)

**Comment by yilmazbahadir** [comment]
We have recently made some changes in the transaction loading/presentation logic, it's in the `dev` branch. Could you try to reproduce it in the current dev branch, I've just tried and couldn't reproduce it. (And if you can reproduce can you share a screentcast?)

**Comment by cryptoBeliever** [comment]
Currently, I'm not able to reproduce on dev. I will close and will reopen if it will happen to me.
