### ISSUE TITLE
When preparing a tx and a previous tx is confirmed, the send fields on a new tx are reset.

### ISSUE THREAD

**Issue by jabo38** [symbol/desktop-wallet#1577]
When I announce a tx, as soon as it is sent, the fields I fill out like "to" or "amount" or "message" get reset to default when the tx is announced. 

I go to fill in more information, and if the previous tx is is confirmed, then the fields are reset to default. 

This happens a lot with multisig txs when trying to initiate one after another.

**Comment by cryptoBeliever** [comment]
Looks fine in dev.

**Comment by cryptoBeliever** [comment]
@bassemmagdy changes from https://github.com/symbol/desktop-wallet/pull/1680 regressed this one.

**Comment by cryptoBeliever** [comment]
Will be fixed in https://github.com/symbol/desktop-wallet/issues/1683
