### ISSUE TITLE
Create subnamespace - visible namespaces for other account if selected account is cosigner

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1587]
Affected versions: 1.0.3, 1.0.4

Preconditions:
- create multisig account (for example 2 of 2)
- create root namespace for multisig account
- create root namespace for cosginer account

Steps:
- go to cosigner with namespace
- go to view Namespaces
- click "Create a sub-namespace"
- switch between cosigner and multisig in From

Result:
In parent namespace selector I can see always namespaces for cosigner even if I have selected multisig account.

Expected result:
In parent namesapce selector I can see:
- cosigner namespaces if I have selected cosigner in From selector
- multisig account namespaces if I have selected multisig account in From selector

Video: https://share.getcloudapp.com/7KuoNZ1E

**Comment by yilmazbahadir** [comment]
Hey @cryptoBeliever, placed a fix. Is this the behaviour you want? 

https://www.loom.com/share/c0ba0e254c034f4a9b63b9abf980dd1e

**Comment by cryptoBeliever** [comment]
@yilmazbahadir yes. it's how it should work

**Comment by cryptoBeliever** [comment]
Fixed in dev branch.
