### ISSUE TITLE
Disable "Use Ledger" button on Create Profile (web)

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1590]
Currently, the web version doesn't support Ledger.
When we tried to create a Ledger profile on the web version there is a tooltip "To use Ledger please download the desktop native app".

![image](https://user-images.githubusercontent.com/17684281/125314763-c7842f00-e336-11eb-8a66-fb2eecebf0a5.png)

Users can still click "Use Ledger" and create a Ledger profile.

Expected result:

- "Use Ledger" button is available for Linux, Mac, Windows, and when developer running `npm run dev`
- "Use Ledger" button is not clickable for web build (https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/download/v1.0.3/symbol-desktop-wallet_1.0.3.all.zip) and tooltip is presented (as is now)

**Comment by fboucquez** [comment]
I think we could add ledger support to web. Maybe just changing the ledger transport? Worth double checking before disabling

**Comment by coiki** [comment]
### Acceptance Criteria
**AC1.** On web and versions where Ledger isn't available, the Ledger button will be visible but disabled.
**AC2.** The tooltip in the current version should remain, and continue showing on hover.

**Comment by cryptoBeliever** [comment]
@yilmazbahadir would be possible to hide text "To use Ledger please download the desktop native app." for all builds except web-generated version (HTML)? Currently, it's presented for all versions and I don't see the reason for that.

**Comment by yilmazbahadir** [comment]
Thanks for the feedback @cryptoBeliever, I think the following PR will fix this issue.

https://github.com/symbol/desktop-wallet/pull/1710

**Comment by cryptoBeliever** [comment]
@yilmazbahadir Thank you! All works as expected.
