### ISSUE TITLE
News feed doesn't work

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1592]
Currently, the news feed is not loading in the desktop wallet. 

It's because in wallet is defined /nemflash which is proxy to https://nemgrouplimited.github.io/symbol-news/
Code:
https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/96b1678b5943b631299511d165d074f4a1219e35/vue.config.js#L84

Currently, the repo was moved to symbol organization.

What has to be done:
- fix in the wallet URLs and replace with https://symbol.github.io/symbol-rss-feeds/

**Comment by coiki** [comment]
@bassemmagdy  proposes to have a redirect of the old project to the new project so older wallets (installbase) are able to see news. If Github project is removed, News will be dead for any wallet that doesn’t update.

@0x6861746366574 do you reckon we can keep the old repo? for the next sprint (maybe even hotfix) we will change it to the new project.

**Comment by 0x6861746366574** [comment]
@coiki Yeah, no reason not to - a fork should be enough, no?

**Comment by cryptoBeliever** [comment]
@bassemmagdy there is a temporary fix that we still kept https://nemgrouplimited.github.io/symbol-news/.
Anyway, please update the link in the wallet to include in the next release.
Thanks

**Comment by cryptoBeliever** [comment]
News feed works fine.
