### ISSUE TITLE
Mosaic is not visible on Supply Change Transaction Page 

### ISSUE THREAD

**Issue by NikolaiB** [symbol/desktop-wallet#1644]
WTR:

1. Go to Aggregate transaction page
2. Click on Supply Change Transaction item
3. Try to choose Mosaic

Result: there are no mosaic to choose despite that I have a few.  
Note: If any aggregate transaction is initiated then mosaic becomes visible.

![image](https://user-images.githubusercontent.com/11311924/128826812-c788869a-4020-4a2d-9dd8-ed94cc240c88.png)

**Comment by bassemmagdy** [comment]
@NikolaiB Was the created mosaic supply mutable? as if it's not there is no point in displaying it on the mosaic supply page.
