### ISSUE TITLE
The same partial tx requests can be send a few times.

### ISSUE THREAD

**Issue by NikolaiB** [symbol/desktop-wallet#1649]
When I am trying to convert simple account into multisig, I can send Partial request to sign transaction a few times. I believe the validation should be added.
![image](https://user-images.githubusercontent.com/11311924/130024356-2e0cd8b4-e1fa-42b1-9bf1-3123390e1b2f.png)

**Comment by cryptoBeliever** [comment]
You can send it a few times but it will be not possible to sign all of them. I'm not sure if this change has sense.

**Comment by yilmazbahadir** [comment]
@cryptoBeliever is right, you should get an error on signing the second one. @NikolaiB what happened when you signed the second one?

**Comment by cryptoBeliever** [comment]
As discussed on call we closing this one. There will be possible issue on Hermes backlog that will allow "reject" (which technically will hide it) partial transaction for user. Currently user is only able to confirm.
