### ISSUE TITLE
Mosaic metadata - possible to select mosaic owned by multisig for cosigner

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1668]
Steps:
1. Crete multisig
2. Add a few mosaics to multisig
3. Go to Mosaics -> Add metadata and select multisig account
4. Choose mosaic owned by multisig
5. Switch to the cosigner
6. Send metadata transaction

Result: It's possible to select mosaic owned by multisig when adding metadata by cosigner.
Expected result: It should be possible to add metadata only for mosaics owne by currently selected account.

Video: https://www.loom.com/share/71a7fb7b988c48b086890ef234ab450c

**Comment by coiki** [comment]
### User Story
As a user that has multiple mosaics, and multiple accounts including multi-sig,
when I am attempting to send mosaics,
I want to see only mosaics I can actually send from the account I am using and nothing else,
so I can always be sure that I'm sending correct mosaics when I'm using the wallet

### Acceptance Criteria

**AC1.** When I am choosing a mosaic to send, I can only see the mosaics I can send from my account.

**Comment by cryptoBeliever** [comment]
Fixed in dev :+1:
