### ISSUE TITLE
Namespace metadata - namespaces selector always present namespaces owned by cosigner

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1669]
Steps:
1. Create multisig
2. Add namespaces to multisig
3. Add namespaces to cosigner
4. Go to Namespaces -> Add metadata
5. Switch to multisig

Result: In selector I can see only namespaces owned by cosigner.
Expected result: In selector I can see namesapces owned by currently selected account.

Video: https://www.loom.com/share/6587562c203e4765824efff7dd82df98

**Comment by coiki** [comment]
### User Story
As a user that has multiple namespaces, and multiple accounts including multi-sig,
when I am interacting with namespaces,
I want to see only namespaces I actually am renting on the account I am using and nothing else,
so I can always be sure that I'm interacting with the right namespaces

Acceptance Criteria
AC1. When I am choosing a namespace, I can only see the namespaces I can operate with from my account.

**Comment by cryptoBeliever** [comment]
Fixed in dev :+1:
