### ISSUE TITLE
Namespaces - list is not refreshed after switch currently selected account

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1670]
Steps:
1. Create multisig
2. Add namespaces to multisig and cosigners
3. Go to Namespaces view -> Add metadata and switch account from cosigner to multisig.
4. Close view

Result: I can still see namespaces for cosigner (but selector is now changed to multisig). I have to click refresh to present correct namespaces.

Expected result: Present namespaces owned by currently selected account.

Video: https://www.loom.com/share/1cdaaac19f8342a787c8e517e9c1255e

**Comment by coiki** [comment]
### User Story
As a user that has multiple namespaces, and multiple accounts including multi-sig,
when I am changing between my multiple accounts,
I want namespaces and other elements to update in line with the account I'm now using,
so I can be sure the information shown is correct and I can operate my wallet correctly.

### Acceptance Criteria
AC1. When I am choosing a Namespace from a dropdown, I want the information shown to always be correct and in line with the account I'm using at the moment.

**Comment by cryptoBeliever** [comment]
Fixed in dev :+1:
