### ISSUE TITLE
Offline transaction getting ERROR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by NikolaiB** [symbol/desktop-wallet#1674]
WTR:

1) Go to offline transaction page

Result: Getting error in console `GET http://mock:3000/statements/transaction?receiptType=8515&targetAddress=TA345SWPBOO4QEWKZA7HRIYMSFMOB3FIMXPYQBI&pageSize=50&pageNumber=1 net::ERR_NAME_NOT_RESOLVED`

![image](https://user-images.githubusercontent.com/11311924/131338959-40a41a42-c6cc-40c8-9dfd-f4e8821f2155.png)

**Comment by cryptoBeliever** [comment]
Fixed in PR https://github.com/symbol/desktop-wallet/pull/1736
