### ISSUE TITLE
Signer selection - change UX

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1688]
Currently signer selection looks like that:

![image](https://user-images.githubusercontent.com/17684281/131698834-caea9814-63ef-43a9-8e7b-39b4275f55b1.png)

Which is not clear when we have multi-level multi-sig or multiple trees.
There was a proposition to change it and make more readable.

Work-In-Progress proposition from @yilmazbahadir:

![image](https://user-images.githubusercontent.com/17684281/131699144-1eef7af4-2c13-4635-a428-93b38ab3ed52.png)

**Comment by yilmazbahadir** [comment]
This is how it is actually going to look, the selection view represents a tree, it starts with the leave (current non-multisig account) then goes to first level msig accounts(branches) and finally to root msig account. Multisig accounts are grouped and inside the group, each line indented according to its level in the tree, most indented ones are the root ones.

![image](https://user-images.githubusercontent.com/6256269/132261836-1d45250c-a6a2-46a3-8596-ec1b2bfdc809.png)

**Comment by cryptoBeliever** [comment]
Fixed in dev.
