### ISSUE TITLE
History view - The home screen is slowed down by a huge transaction history.

### ISSUE THREAD

**Issue by vistiel** [symbol/desktop-wallet#1696]
** issue **
The history in the home screen tries to show all the huge transaction history.
This makes the process very costly and negatively affects the response time.

I think it should be displayed by page, and the number of items displayed per page should be configurable.

** environment **
Symbol Wallet v1.0.6

**Comment by cryptoBeliever** [comment]
Hi. Thank you for your report. It's duplicate of: https://github.com/symbol/desktop-wallet/issues/1652 which will be resolved in current sprint. Please observe issue #1652
