### ISSUE TITLE
Partial transactions cannot be shown correctly in the transaction history

### ISSUE THREAD

**Issue by yilmazbahadir** [symbol/desktop-wallet#1697]
In the transaction view, partial transactions cannot be shown correctly for the cosigner(for multi-level multi-sig accounts). It's random, when refreshed sometimes it appears in the list sometimes not.

https://www.loom.com/share/08b3416c8a7b4db8a8160802ae427e0d

**Comment by cryptoBeliever** [comment]
I'm not able to to reproduce anymore in dev :+1:
