### ISSUE TITLE
Contact information is not reflected correctly

### ISSUE THREAD

**Issue by shimane-ishida** [symbol/desktop-wallet#1718]
I have registered my address as a contact named "My Address".
However, when I look at the aggregated details of the combined transactions, the destination in the first row shows "My Address", but the source in the second row is still the address string.

![スクリーンショット 2021-09-29 125235](https://user-images.githubusercontent.com/14101506/135201093-8a8e3003-5e45-40b5-a09c-aea06b3c980c.png)

**Comment by cryptoBeliever** [comment]
It's fixed in https://github.com/symbol/desktop-wallet/pull/1847

**Comment by cryptoBeliever** [comment]
Fixed in 1.0.11
