### ISSUE TITLE
Password is not inserted(control+v) when creating a wallet or when importing a wallet version (1.0.6)

### ISSUE THREAD

**Issue by klimgeran** [symbol/desktop-wallet#1722]
Password is not inserted(control+v) when creating a wallet or when importing a wallet version (1.0.6)

https://user-images.githubusercontent.com/30126937/135251665-ef666db4-e59f-49fa-b3d3-2f9f1e5ce7c5.mov

___
macOS Big Sur v.11.6

___
Symbol wallet version (1.0.6)

**Comment by cryptoBeliever** [comment]
This behaviour is expected. Issue: https://github.com/symbol/desktop-wallet/issues/1167
