### ISSUE TITLE
Secret locks not visible in transaction details

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1726]
Example code (https://github.com/symbol/desktop-wallet/issues/1719#issuecomment-929928841):

When announcing such aggregate with secret lock wallet is not showing SecretLock in tx details (this aggregate contains secret lock and transfer transaction) at all:

![image](https://user-images.githubusercontent.com/17684281/135408932-dab015a0-6ff9-4c23-a1cf-d12756e52a61.png)

**Comment by bassemmagdy** [comment]
fixed in https://github.com/symbol/desktop-wallet/pull/1744
