### ISSUE TITLE
Harvesting status doesn't change to Active while activating via the mobile app

### ISSUE THREAD

**Issue by NikolaiB** [symbol/desktop-wallet#1731]
WTR:

1) Go to mobile wallet with enough account importance for harvesting
2) Activate harvesting
3) Open the same account on desktop wallet

Result: you can see that harvesting status was not updated.
![image](https://user-images.githubusercontent.com/11311924/135961110-086493f9-963b-40e7-8777-fbad0c2b7bf3.png)

Related issue: https://github.com/symbol/mobile-wallet/issues/226

**Comment by cryptoBeliever** [comment]
Fixed in 1.0.9 (https://github.com/symbol/desktop-wallet/issues/1762).
Now desktop wallet is presenting the correct status even if it was activated on another device.
