### ISSUE TITLE
Changes to be made to address book 2.0

### ISSUE THREAD

**Issue by surekabpm** [symbol/desktop-wallet#1739]
Allow to import/export lists.
There are blacklisted contacts that will activate restrictions for that address.
A community-maintained list with known bad actors will be made available and recommended through SNS.

**Comment by bassemmagdy** [comment]
@surekabpm we would need access to the address-book repository.

**Comment by coiki** [comment]
@bassemmagdy @cryptoBeliever  adding literature here

## Background

We want to increase the functionality of the address book and turn it into a powerful tool that allows the Symbol community to operate even more safely.

The Symbol wallet’s address book will allow to import and export lists of contacts. Contacts can be blacklisted (blocks all incoming transactions, like spam), or regular contacts.

This should allow the community to constantly be up to date on what is happening in the Symbol ecosystem. For example, users can add to their address book the most recent XYM project, or block a known spammer.

Please check this figma file to find the screens that represent this points: https://www.figma.com/file/lkhDQWxq5FlUrMNZYIJ2wT/Symbol-Wallet---Legacy?node-id=209%3A29026

### Acceptance Criteria

- AC1: Add to blacklisted after rejectinging a receiving transaction: As a user that just decided to reject a receiving transaction, I want to be asked to blacklist that address, so I can safely operate without disturbance from bad actors
- AC2: Allow importing of address book lists: As a user, I want to import an address book, adding all its contents to my own address book, so I can grow my list of contacts and blacklisted contacts from the community knowledge or someone’s I trust.
- AC3: As a user importing an address book, I want it to be added to my local address book so it does not replace my local address book, just appends to it, so I can continue to grow mine and expand it.
- AC4: Add to address book after sending a transaction: As a user that just finished sending and signing a transaction, I want to be asked to add that address to my address book, so I can add it and easily

**Comment by cryptoBeliever** [comment]
Adding diagram which flow we should show depends on signer trust level:

![image](https://user-images.githubusercontent.com/17684281/153926654-6d809970-793a-4c50-a066-6203144d6f90.png)

1. Signer is in contacts (whitelisted) or it's from user multi-sig structure. We present only passwords.
2. Signer is unknown. We present flow as in on Figma with an option to Accept/Reject.
3. Signer is blocked. We present information about blocked signer with an option to unblock.
