### ISSUE TITLE
Use openapi-client for calls to statistics service

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1757]
In NodeService.js we calling statistics service for node list:
```
const data = await requestNodes(networkType, nodeSearchCriteria);
```
It should be replaced top openapi-client (symbol-statistics-service-typescript-fetch-client).

Example in bootstrap: https://github.com/symbol/symbol-bootstrap/blob/c846846245e02d8886fac5985374da0a15b05a83/src/service/RemoteNodeService.ts#L136

If same is needed in mobile (https://github.com/symbol/mobile-wallet/pull/246) please open seperate issue in mobile wallet repository (https://github.com/symbol/mobile-wallet/issues)

**Comment by bassemmagdy** [comment]
duplicate of https://github.com/symbol/desktop-wallet/issues/1776

**Comment by cryptoBeliever** [comment]
Duplicate of https://github.com/symbol/desktop-wallet/issues/1776
