### ISSUE TITLE
Copyrights to be changed as Symbol

### ISSUE THREAD

**Issue by surekabpm** [symbol/desktop-wallet#1761]
In the Desktop wallet the copyrights need to be changed to symbol wherever required as

**Comment by surekabpm** [comment]
![image](https://user-images.githubusercontent.com/49143210/140065530-8640b547-031f-4380-aabf-2cfab092ffda.png)

**Comment by surekabpm** [comment]
It has to be (C) Symbol Contributors 2021( as per discussion with Kristy )

**Comment by cryptoBeliever** [comment]
Fixed in #1772
