### ISSUE TITLE
send- when sending anything other than a currency mosaic, the UI displays there is not enough balance

### ISSUE THREAD

**Issue by monakaJP** [symbol/desktop-wallet#1771]
When sending anything other than a currency mosaic, UI displays "Not enough balance" even if address has enough mosaic balance .

**Comment by bassemmagdy** [comment]
Hi @monakaJP thanks for reporting, could you elaborate more, maybe add screenshots if possible?

**Comment by monakaJP** [comment]
Thank you for reply. This is screenshot.
![a](https://user-images.githubusercontent.com/85240742/142096237-425cf9cd-5404-41c8-99e9-65efabf91594.JPG)

**Comment by monakaJP** [comment]
> Hi @monakaJP thanks for reporting, could you elaborate more, maybe add screenshots if possible?
Thank you for reply. This is screenshot
![a](https://user-images.githubusercontent.com/85240742/142096393-b3717d26-a260-4296-9446-4ee63632a73c.JPG)

**Comment by bassemmagdy** [comment]
Have you done some specific steps to reproduce? as I can see your `xembook.tomato` mosaic has a balance of 741, on the other hand, there is a 0 displayed in amount input which should be 741 too.

**Comment by monakaJP** [comment]
> Have you done some specific steps to reproduce? as I can see your `xembook.tomato` mosaic has a balance of 741, on the other hand, there is a 0 displayed in amount input which should be 741 too.
This is screenshot of input 741 xembook.tomato.
When I select use maximum value button, amount was changed 0 xembook.tomato
![a](https://user-images.githubusercontent.com/85240742/142105666-8c4d7a38-7dc9-4409-a09e-06321d65aab5.JPG)
.

**Comment by NikolaiB** [comment]
WTR:
1) Create mnemonic with 1 mosaic
2) Go to the home page
3) Add recipient address
4) Select mnemonic with 1 mosaic
Result: the max balance shows 0
https://www.loom.com/share/38040f500a0c4c6c945ab60cfca80852

**Comment by bassemmagdy** [comment]
@monakaJP Thanks for reporting, we will address this shortly.
