### ISSUE TITLE
Login problem. 

### ISSUE THREAD

**Issue by Eunchan24** [symbol/desktop-wallet#1792]
I can't log in for 30 minutes.
I entered the ID and password correctly and it doesn't move on from loading.
![image](https://user-images.githubusercontent.com/71329051/143510705-41746919-83ea-47fa-953a-4452ed517146.png)

**Comment by bassemmagdy** [comment]
Hi @Eunchan24, thanks for reporting.
are you using the latest version? also, are you using the standalone or browser version?

**Comment by Eunchan24** [comment]
The app version is 1.0.3 and it's standard.

**Comment by bassemmagdy** [comment]
Thanks for letting us know, you need to be using the latest version [1.0.8](https://github.com/symbol/desktop-wallet/releases/tag/v1.0.8).
Closing the issue, please re-open or create a new one if you still have problems with the latest.
