### ISSUE TITLE
The defaultTestnetNetworkConfig is out of date because the testnet was reset.

### ISSUE THREAD

**Issue by cndlhvn** [symbol/desktop-wallet#1809]
Hi, I tried to cosign an offline transaction, but the configuration of this testnet was outdated. For example, the generationHash value seems to be before the reset. Please update.

https://github.com/symbol/desktop-wallet/blob/3e3f46f184e4700e52fd4b5520b91dcdd6e3f510/src/config/NetworkConfig.ts#L53

**Comment by cryptoBeliever** [comment]
Yes. We are aware, will be fixed in 1.0.9: https://github.com/symbol/desktop-wallet/pull/1808/files

**Comment by cryptoBeliever** [comment]
Prepared to release.
