### ISSUE TITLE
Can not request Harvesting

### ISSUE THREAD

**Issue by NikolaiB** [symbol/desktop-wallet#1812]
WTR:

1) Go to the Harvesting page
2) Click `Link the key` button
3) Click `Request Harvesting` button

Result: I can see two password popups instead of request harvesting
Video: https://www.loom.com/share/e03182b477dd4a8f8549e01ed803f2b2

**Comment by cryptoBeliever** [comment]
Not sure if this is P1 because it should work when you go to another view and go back.
