### ISSUE TITLE
[AddressBook] UI issues

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1823]
List of UI issues (https://github.com/symbol/desktop-wallet/pull/1814):

If something was decided to look different than on Figma please just comment.

1. [x] Go to the address book and click "Add contact". Result: New contact pop-up shows and buttons "Add contact" and "Backup address book". I would expect that buttons will stay in their place.

Before you click "Add contact":

![image](https://user-images.githubusercontent.com/17684281/149381823-f37affff-e117-4443-81e7-a3b79d3b61a9.png)

After "Add contact" clicked:

![image](https://user-images.githubusercontent.com/17684281/149381890-97d99f63-78e7-40b3-b48d-a368b72b11df.png)

2. [x] Whitelist | Blacklist header. Tab selection purple underscore is wider than on Figma. Also looks like the underscore is higher on Figma.

Figma: 
![image](https://user-images.githubusercontent.com/17684281/149382326-5f96caba-4349-452e-b08d-55002afbe8a7.png)

Wallet:
![image](https://user-images.githubusercontent.com/17684281/149382605-40a6f79c-9d9e-4572-b7d7-9f7f1d60eb7a.png)

3. [x] Single contact item size/text fonts are bigger in the wallet than in Figma. This causes fewer items to fit the screen.

Figma:
![image](https://user-images.githubusercontent.com/17684281/149383451-9eb5b327-1f92-41b1-ad86-6cc55ae8dc26.png)

Wallet:
![image](https://user-images.githubusercontent.com/17684281/149383389-2597183a-e606-4b07-bf93-633b1ba45402.png)

4. [x] Contact name ("Symbol NFT Marketplace") is cut but there is plenty of space to show it (entire space should be used).

Figma:
![image](https://user-images.githubusercontent.com/17684281/149383730-908924a3-e284-49e1-8276-cb103ba42a28.png)

Wallet:
![image](https://user-images.githubusercontent.com/17684281/149383766-12e5d3d9-e3e1-49a6-84c5-af602671810c.png)

5. [x] In the wallet there are horizontal lines between contact items (can be seen on screenshots above). In Figma, there are no such items.

6. [x] On Figma in blacklist contact address is on top and name on the bottom. As I understand this is a mistake on Figma? In the wallet, it's the same as for the whitelist (name top, address bottom).

7. [x] Signing partial transaction. View Transaction requires a signature:

- There is another message "Transaction requires signature" vs "Transaction awaiting co-signature(s)". It's expected?
- Button size is different than on Figma. 
- Accept button text on Figma is "Accept..." instead "Accept"
- Left side of Reject button and text above should be aligned with transaction details left side

Figma:
![image](https://user-images.githubusercontent.com/17684281/149387190-89d62844-a39a-4a18-ba0e-5ae6eae41f2a.png)

Wallet:
![image](https://user-images.githubusercontent.com/17684281/149387135-aa3ab9a1-78b5-4f75-b6c0-36ed3b46a385.png)

8. [x] Similar issues as above with "Reject" view

- Alignment, Text size, button size
- I would change "New contact name" to "Contact name" or "Name"

Figma:
![image](https://user-images.githubusercontent.com/17684281/149387818-f485962b-6ddf-412d-b733-e0e0cbe74e22.png)

Wallet:
![image](https://user-images.githubusercontent.com/17684281/149387798-f082aef7-6d2f-4dbb-b6bb-c3aeee64ee9e.png)

9. [x] Caution screen:

- Missing image with "Caution" text
- Again similar issues with alignment and size. 
- I think that Password controls (label, input, button) should show after the user accept the checkbox. What do you think @coiki ?
- Password form is other than on Figma (on Figma on entire page). Is that expected?
- When I click checkbox I have effect like this:
![image](https://user-images.githubusercontent.com/17684281/149388573-b15d8901-53f6-4285-8070-7dc7da9357df.png)
- on Figma, there is "I understand" in wallet "I understand and wish to proceed".

Figma:
![image](https://user-images.githubusercontent.com/17684281/149388032-1d533340-3fd6-4ee6-b5ee-4da3452d350f.png)

Wallet:
![image](https://user-images.githubusercontent.com/17684281/149388070-d2221b6a-db11-4f95-b702-07088d46ea67.png)

10. [x] Add new address after signing partial:

- We agreed to change text "Transaction signed and confirmed by network." to "Transaction successfully sent. Pending to be confirmed by the network."
- Currently "Show in the explorer" links to Account but should Link to transaction

![image](https://user-images.githubusercontent.com/17684281/149393202-e864ee74-3a14-4798-8775-ea2404a9e9c2.png)

**Comment by NikolaiB** [comment]
11. When Aggregate transaction was initiated from the blacklisted address, it can not be signed, but when the address is changed to whitelist it still has no field to sign the transaction.

**Comment by bassemmagdy** [comment]
Addressed all issues in PR #1814 except 6 (I believe it was a mistake on figma) and 9 as images with suitable sizes not ready yet.

**Comment by cryptoBeliever** [comment]
1. Fixed
2. Looks better. Still underscore on Figma is a bit wider than the text above. If it's easy to fix, we could do that.
3. Still looks like items are higher than on Figma. From Mosaic to Aggregate on Figma it fits 5 elements but after a change on desktop wallet only 4. Could you verify that? Maybe it's icon size or maybe a white break between elements.
4. Fixed
5. Fixed
6. Ok. Assume its mistake on Figma.
7. Fixed
8. There is a missing question mark in the text.
9. Ok. As I understand it will be fixed with images (still problem with checkbox when checked, alignment). @coiki  what do you think about showing password input on checkbox selection.
10. When pop-up with "New address detected" address is grey. Could you make it disabled but more visible?

**Comment by NikoCyber** [comment]
@cryptoBeliever @bassemmagdy maybe it makes sense to increase the size of letters? In my opinion they are too small, hardly visible. Or to show a full address, otherwise we have empty space in column 
![image](https://user-images.githubusercontent.com/11311924/150025813-2b571dc0-59e9-4a5a-9136-fb4ce1b17b5d.png)

**Comment by NikoCyber** [comment]
@cryptoBeliever @bassemmagdy Able to Export Blacklisted transactions despite that `Show blacklisted transactions` button was not selected.

**Comment by bassemmagdy** [comment]
>   Able to Export Blacklisted transactions despite that `Show blacklisted transactions` button was not selected.

@NikoCyber Why do you expect them to be excluded in exported transactions?

> maybe it makes sense to increase the size of letters? In my opinion they are too small and we have design mismatch with My Accounts. + we could show the full address, otherwise we have empty space in column.

I agree on the design mismatch part as in my accounts we have this with horizontal line separator and different dimensions:
<img width="345" alt="Screen Shot 2022-01-19 at 4 02 16 AM" src="https://user-images.githubusercontent.com/9143194/150049705-7c74bb30-a37a-494b-bfad-58abdef8c256.png">
but in my contacts which should look alike AFAIU, we got this 
<img width="363" alt="Screen Shot 2022-01-19 at 4 02 20 AM" src="https://user-images.githubusercontent.com/9143194/150049756-053e56a8-8be6-49bb-8a25-fd955cbca731.png">
@cryptoBeliever @coiki If we want to proceed with that please reopen a new issue for aliging the other menus according to new design.

**Comment by bassemmagdy** [comment]
> 1. Fixed
> 2. Looks better. Still underscore on Figma is a bit wider than the text above. If it's easy to fix, we could do that.
> 3. Still looks like items are higher than on Figma. From Mosaic to Aggregate on Figma it fits 5 elements but after a change on desktop wallet only 4. Could you verify that? Maybe it's icon size or maybe a white break between elements.
> 4. Fixed
> 5. Fixed
> 6. Ok. Assume its mistake on Figma.
> 7. Fixed
> 8. There is a missing question mark in the text.
> 9. Ok. As I understand it will be fixed with images (still problem with checkbox when checked, alignment). @coiki  what do you think about showing password input on checkbox selection.
> 10. When pop-up with "New address detected" address is grey. Could you make it disabled but more visible?

@cryptoBeliever 2 is not as easy to control border's length, (3-8-10) should be fixed.
- for (9) we can have that as a separate PR

**Comment by cryptoBeliever** [comment]
>  we could show the full address, otherwise, we have empty space in column
@NikoCyber I agree that we should show the full address if we can present it (there is space)
@bassemmagdy @NikoCyber regarding how it looks compared to accounts view I think it's a question to @coiki and Biagio (I just commented difference between what is done and Figma screens). 

> Able to Export Blacklisted transactions despite that Show blacklisted transactions button was not selected.
@NikoCyber I think we should export all same as other filters that don't work on exported tx. I think users want to see all there as a account full history. From other side CSV export requires a lot of improvements.

**Comment by cryptoBeliever** [comment]
Ad8. @bassemmagdy Please change "New contact name" to "Name
Ad9. @coiki please have a look if we want to change something here (maybe we should show password input when user click "I understand")?. In Figma, this screen looks different.

When the "I understand" checkbox is not checked:

![image](https://user-images.githubusercontent.com/17684281/151117036-cc0b1d76-d6f7-49b5-900c-bea7f0b97570.png)

When the "I understand" checkbox is checked:

![image](https://user-images.githubusercontent.com/17684281/151117175-0012dda2-25c9-433f-a53c-9e098f32a06f.png)

@bassemmagdy checkbox looks bad (additional white part) when we "check" it:

![image](https://user-images.githubusercontent.com/17684281/151117360-2970704f-c909-44cf-b0dd-8d2731767651.png)

**Comment by cryptoBeliever** [comment]
@OlegMakarenko what left:

9. Caution screen:
- missing image with "Caution" screen
- I think Password controls (label, input, button) should show after the user accept the checkbox.
- When I click the checkbox, I got strange artifact under it.
- Clicking in "I understand" should check the checkbox too.
10. New address detected screen:
- We show address added in grey. It's not fully visible. Would be possible to show the entire password?
11. We changed "Blacklist" to "Block". Not sure if we want to change it also in the address book.

**Comment by cryptoBeliever** [comment]
@OlegMakarenko great job! What I noticed:
- There is still a missing image (above orange area) for the "Caution" screen. We don't have this image? Did you ask Bassem?
- Account -> My contacts. We have still a whitelist/blacklist (buttons and headers) there. You decided to keep it because it's more clear?
- Account -> My contacts. If you click "Add contact" or "Import address book" buttons jump above.
- Home -> History. There is a skull filter there for blocked transactions. Alt text is "Show blacklisted transactions", should be "Show blocked transactions"
