### ISSUE TITLE
[AddressBook] Not possible to sign bonded for multisig

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1824]
Steps (here example of creating multisig):

1. Create two accounts (at least this one which we will try to convert to multisig should have XYM)
2. Go to the cosigner to sign it
3. Open transaction details. 

Result:
There is no way to sign a transaction:

![image](https://user-images.githubusercontent.com/17684281/149390398-d1afd892-a430-4e6f-b5af-94af79b36688.png)

**Comment by NikolaiB** [comment]
@cryptoBeliever Could you verify it again, for me it works now.

**Comment by cryptoBeliever** [comment]
Yes. Bassem fixed that already.
