### ISSUE TITLE
[AddressBook] Transaction blacklist filter

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1825]
Issues:

1. In my opinion each time you return to transaction history then the filter should be reset to false. It's a bit confusing that it stays selected even if I change screens or even accounts. I think the safest way is to reset it each time user will change the view.

2. (probably will be solved automatically after fix 1):
Steps:
- go to account A transaction history
- turn on blacklisted filter
- switch to account B
Result: I can see all transactions when the blacklist filter is selected. Even if I don't have any blacklisted contacts. To fix that I have to turn off and on again blacklist filter.

3. After receiving partial/unconfirmed transactions on history view it's not filtered.
Steps:
- go to history view
- send a transaction from another address
- after receiving the transaction it is always presented on the list even if I have the blacklist filter off and transaction should be blacklisted

4. If the blacklist is empty then "Show blacklisted transactions" changes nothing. No matter if it's active or not I can see full history.

**Comment by cryptoBeliever** [comment]
@bassemmagdy 
1. Fixed
2. Fixed
3. Could you tell me which one field is used to filter transaction? Is this signer? Sometimes it works weird for me.
4. Still have the same issue.

**Comment by bassemmagdy** [comment]
@cryptoBeliever 
3 - Yes it's the signer.
4- Such a behavior should be fixed now.

**Comment by cryptoBeliever** [comment]
Ad3. I don't know why but it doesn't work for me.

I have blacklisted contact:

![image](https://user-images.githubusercontent.com/17684281/151119516-4d4a68c2-1990-4086-904f-26b5fa1e4b5d.png)

But no transaction bonded from this address was blacklisted:

![image](https://user-images.githubusercontent.com/17684281/151119595-b3c9a672-08bc-45e4-af39-4e5d7d8cab0b.png)
![image](https://user-images.githubusercontent.com/17684281/151119640-08daa00c-0816-4f3a-b7bb-29bb0c4e0e3b.png)

Private key to address: D411D128C38FD10A4D456AF2F34DF8452EA68766624CABBC412E61F7873A663B
I attached also export from address book (you have to change .txt to .json)

[address-book_backup.txt](https://github.com/symbol/desktop-wallet/files/7939623/address-book_backup.txt)

**Comment by cryptoBeliever** [comment]
3. Ok. I had some issues but it looks like same as here https://github.com/symbol/desktop-wallet/issues/1831
4. Fixed.
