### ISSUE TITLE
[AddressBook] Adding to blacklist improvement

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#1826]
Currently, to manually blacklist address in the address book you have to do the following steps:
1. Go to Account -> My contacts
2. Add account
3. Put contact name and address -> Confirm
4. Select contact on the whitelist
5. Select "Blacklist" on the contact details page

I think we should allow user to add right away into blacklist (without requesting first add to whitelist and next move from whitelist to blacklist).

**Comment by cryptoBeliever** [comment]
@coiki could you look at this? If this is to do for next release?

**Comment by coiki** [comment]
@cryptoBeliever thank you, I checked both tasks and this one has a higher priority over #1827 although both should be in the next release 👍

**Comment by cryptoBeliever** [comment]
Fixed in https://github.com/symbol/desktop-wallet/pull/1847
