### ISSUE TITLE
Having unsigned partial transactions from UI that can not be removed

### ISSUE THREAD

**Issue by NikolaiB** [symbol/desktop-wallet#1828]
WTR:

1. Create multisig account
2. Initiate a few times aggregate to remove co-signor
3. Finally sign the transaction

Result: A few transaction stays unassigned from UI 
![image](https://user-images.githubusercontent.com/11311924/149613626-4c768d4a-0e07-4b4d-ace1-89298bcfac41.png)

**Comment by cryptoBeliever** [comment]
It's not a wallet bug. Wallet just shows partial returned by rest. Those redundant not signed partials will be dropped after the transaction will expire.
The wallet could block sending the same removal transactions but it's not a philosophy that is implemented in the wallet currently. We assume that the user knows what he is doing and how a multi-sig account works (that rest of the required cosigners have to sign it).
