### ISSUE TITLE
[Address Book] Contacts with an empty name is not presented in the forms

### ISSUE THREAD

**Issue by OlegMakarenko** [symbol/desktop-wallet#1846]
![image](https://user-images.githubusercontent.com/33131259/154048993-61f4b90b-1ff4-4574-a38e-bda2a781b70c.png)

**Comment by OlegMakarenko** [comment]
@cryptoBeliever there are two options how to resolve this: 
1. When the name field is empty, display the contact's address instead.
2. Prevent the contact from being added to the black list if the name is not entered.
![image](https://user-images.githubusercontent.com/33131259/154049859-71c6e07e-8b10-4920-8cc1-3739aa1ae2b5.png)

**Comment by cryptoBeliever** [comment]
@OlegMakarenko name should be required.

**Comment by cryptoBeliever** [comment]
Fixed in https://github.com/symbol/desktop-wallet/pull/1847
