### ISSUE TITLE
Language: en-US has dup keys. "transaction_descriptor_17229"

### ISSUE THREAD

**Issue by 44uk** [symbol/desktop-wallet#1961]
https://github.com/symbol/desktop-wallet/blob/dev/src/language/en-US.json#L1056

```json
"transaction_descriptor_17229": "Reclaim",
```

https://github.com/symbol/desktop-wallet/blob/dev/src/language/en-US.json#L1062

```json
"transaction_descriptor_17229": "Mosaic supply revocation",
```

**Comment by cryptoBeliever** [comment]
@44uk fixed in dev branch
