### ISSUE TITLE
YOUR ACCOUNT CANNOT START DELEGATED HARVESTING WHILE IMPORTANCE IS EGAL TO 0

### ISSUE THREAD

**Issue by NeaPat** [symbol/desktop-wallet#1989]
Bonjour, mon compte Symbol sur le programme de bureau est connecte avec ma Ledger NX, Je ne parviens pas à passer le stade 4:
"Saisissez votre mot de passe et cliquez sur « Confirmer » .
Le Desktop Wallet signera alors la transaction et l'annoncera au réseau . Au bout d'un moment (cela ne devrait pas prendre plus de 30 secondes), l'écran devrait se mettre à jour :" et après avoir appuyer sur confirme, il apparait toujours la fenêtre en haut a gauche en rouge avec la mention "YOUR ACCOUNT CANNOT START DELEGATED HARVESTING WHILE IMPORTANCE IS EGAL TO 0"
J'ai changé trois fois de "noeux dans la liste", et au final mis "Average" pour les "fee", mais sans succès.
Auriez vous une explication svp?

**Comment by NeaPat** [comment]
Hello, my Symbol account on the desktop program is connected with my Ledger NX, I cannot pass stage 4:
"Enter your password and click "Confirm".
The Desktop Wallet will then sign the transaction and announce it to the network. After a while (it shouldn't take more than 30 seconds), the screen should update: "and after pressing confirm, the window still appears at the top left in red with the mention " YOUR ACCOUNT CANNOT START DELEGATED HARVESTING WHILE IMPORTANCE IS EQUAL TO 0"
I changed three times from "nodes in the list", and in the end put "Average" for the "fee", but without success.
Would you have an explanation please?
![2023 07 07 SYMBOL WALLET BUREAU SOLDE ](https://github.com/symbol/desktop-wallet/assets/95469552/7795719c-45a3-4f7c-8c02-e355e909b8d3)

**Comment by NeaPat** [comment]
[2023 07 07 015 SYMBOL XYM Récolte HARVESTING NOEUX autre PB IDEM .pdf](https://github.com/symbol/desktop-wallet/files/11979483/2023.07.07.015.SYMBOL.XYM.Recolte.HARVESTING.NOEUX.autre.PB.IDEM.pdf)

**Comment by cryptoBeliever** [comment]
You have to wait until iportance recalculation. You should be able start harveting after 12h when you receive above 10,000 XYM.
