### ISSUE TITLE
Usability Inspection and Analysis - Create Profile Screen (13 UX issues)

### ISSUE THREAD

**Issue by fullcircle23** [symbol/desktop-wallet#451]
I'm no UX expert but noticed several issues and wanted them to be caught sooner rather than later. So I've done a usability inspection and analysis of **Create Profile Screen** and putting out the findings here for review/discussion and resolution. I've identified 13 UX issues. Some of these are straightforward and can be fixed right away, some may need to be discussed first either here or in the weekly call.

Screenshots:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/33846962/86778484-0250e880-c08d-11ea-925b-a343ef35f1a3.png">

| GitHub Issue | No. | ID | Issue Description | Recommendation
| -- | -- | -- | -- | --
|  | 1 | 1 | Missing product name and version. | • Add label `Desktop Wallet` with version number. • Version number should be in smaller font and lower contrast with the background so that it doesn't stand out too much. • Add mouseover tooltip to display full product name and version.
|  | 2 | 2 | Missing Help/Support feature. | • Add Help/Support feature. • Use question mark icon button. • Use mouseover tooltip `Support`.
|  | 3 | 3 | Console implies text entry but this is only for displaying client logs. | • Use a read-only console icon instead of the label `Console`. • Add mouseover tooltip `Client Logs`.
|  | 4 | 4 | Network type button lacks visual feedback. | • Highlight the button on mouseover. • Add mouseover tooltip `Network Type`.
|  | 5 | 5.1 | Language button lacks visual feedback. | • Highlight the button on mouseover. • Add mouseover tooltip `Language`.
|  | 6 | 5.2 | Displaying the full name of the language results in varying width, takes up more space, and unnecessary. | • Use ISO 2 Letter Language Code. • Display full name of language in the dropdown list.
|  | 7 | 6.1 | Settings button lacks visual feedback. | • Highlight the button on mouseover. • Add mouseover tooltip `Settings`.
|  | 8 | 6.2 | Users are familiar with the Sign- up/Sign-in/Sign-out buttons placed on the top right of website/ app headers.Placing the Settings button in this location of the header does not take advantage of this common pattern which can be carried out throughout the entire app. | • Shift the Settings button to the left and place `Create profile` dropdown menu in the location where the Setting button was. • The dropdown will be the same list of different methods to create a profile in the middle of the page.
|  | 9 | 7 | The title and description is inaccurate. User came to this page because user does not have a saved profile, hence, will not be able to login. | Change `Access my profile` to `Create a profile`.
|  | 10 | 8 | Same as 7. | • Remove the line `Do you already have a profile? Click here to login now`• Add appropriate description for `Create a profile`
|  | 11 | 9 | `Mnemonic` is a jargon and not accurate in its use here. | • Change `Create Mnemonic` to `Create profile`. • Change `Create a new profile` to `Create your new HD Wallet profile`
|  | 12 | 10 | Because we are actually restoring the wallet, the profile name is arbitrary.Instead of `mnemonic`, we should say `secret 24-word phrase` which is more meaningful and understandable. | • Change `Import mnemonic` to `Restore wallet`. • Change `Import a mnemonic passphrase to create a profile` to `Restore your HD Wallet from your secret 24-word phrase`
|  | 13 | 11 | Decreasing the width of the window (11a in Appendix) causes all the UI elements within it to scale down to the point that the buttons on the header becomes illegible when window is only at half width. Decreasing the window height (11b in Appendix) does not cause such issues. | Instead of scaling down, the UI elements should be able to switch from a horizontal layout to a vertical layout thus preserving readability.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/33846962/86783787-56f76200-c093-11ea-9a70-9f5d329fda42.png">

<img width="762" alt="image" src="https://user-images.githubusercontent.com/33846962/86783859-670f4180-c093-11ea-94e0-95c17c97cf04.png">

For further details, please refer to PDF:
[UsabilityInspection-DesktopWallet-CreateProfile-Rel-1.2.pdf](https://github.com/nemfoundation/symbol-desktop-wallet/files/4884953/UsabilityInspection-DesktopWallet-CreateProfile-Rel-1.2.pdf)

Note:
I've created a separate tickets for the usability inspection/analysis of the following:
- the interactions originating from the Create Profile Screen.
- the Home screen.

**Comment by cryptoBeliever** [comment]
@OlegMakarenko wallet changed a lot since issue creation. Do you think we can apply something with these changes (Also #452 and #453)?

**Comment by coiki** [comment]
Closing since some points don't apply. New tasks will be created for any valid points.  See #453
