### ISSUE TITLE
Usability Inspection and Analysis - Modals, Network Type, Settings (5 UX issues)

### ISSUE THREAD

**Issue by fullcircle23** [symbol/desktop-wallet#452]
Following on from #451, this is the usability inspection and analysis of these 3 interactions. 5 UX issues have been identified. The numbers and boxes map in the screenshots refers to the ID column in the Findings table.

<img width="442" alt="image" src="https://user-images.githubusercontent.com/33846962/86787886-2534ca00-c098-11ea-8292-3f35f20ec848.png">

<img width="443" alt="image" src="https://user-images.githubusercontent.com/33846962/86787911-2cf46e80-c098-11ea-80d9-d5b9afcde175.png">

<img width="472" alt="image" src="https://user-images.githubusercontent.com/33846962/86787950-341b7c80-c098-11ea-8293-73e8e17faeb3.png">

### Findings table

| GitHub Issue | No. | ID | Issue Description | Recommendation
| -- | -- | -- | -- | --
|  | 14 | 1 | Modal windows that do not need user input should not show the `Cancel` and `OK` buttons. | Change to a single `Close` button.
|  | 15 | 2 | Inconsistent casing. | Change `current_network` to `Current Network`.
|  | 16 | 3 | Missing space. | Insert space between nodes and left bracket. E.g. `List of nodes (7)`
|  | 17 | 4 | Unable to scroll list using Up and Down arrow keys. | Enable Up and Down arrow keys to scroll list.
|  | 18 | 5 | Modals that need user input must also have a `Cancel` option. | Add `Cancel` button.

For further details, please refer to PDF:
[UsabilityInspection-DesktopWallet-CreateProfile-Rel-1.2.pdf](https://github.com/nemfoundation/symbol-desktop-wallet/files/4884953/UsabilityInspection-DesktopWallet-CreateProfile-Rel-1.2.pdf)

Note:
1. The Create Mnemonic / Import Mnemonic / Import Private Key will be covered separately.
2. I've created a separate tickets for the usability inspection/analysis of the following:
- Create Profile Screen #451
- Home screen

**Comment by coiki** [comment]
Closing since some points don't apply. New tasks will be created for any valid points.  See #453 .
