### ISSUE TITLE
Usability Inspection and Analysis - Home Screen (16 UX issues)

### ISSUE THREAD

**Issue by fullcircle23** [symbol/desktop-wallet#453]
Following on from #451 and #452 , this is the usability inspection and analysis of the Home screen. 

I've listed 16 UX issues to be discussed and/or taken up individual issue tickets. 

The numbers and boxes in the screenshots below refers to the ID column in the Findings table.

<img width="989" alt="image" src="https://user-images.githubusercontent.com/33846962/86790620-36330a80-c09b-11ea-8fb8-8e2417465be8.png">

<img width="986" alt="image" src="https://user-images.githubusercontent.com/33846962/86790755-55319c80-c09b-11ea-82e0-bebfc03f34dd.png">

### Findings table

| GitHub Issue | No. | ID | Issue Description | Recommendation
| -- | -- | -- | -- | --
|  | 1 | 1 | Users are familiar with the Sign- up/Sign-in/Sign-out buttons placed on the top right of website/ app headers.<br>Placing the Account Name dropdown menu in this location does not take advantage of this common pattern which can be carried out throughout the entire app. | Place the Profile Name dropdown menu here. The dropdown menu could have links to the following actions:<br>- Settings<br>- Change password<br>- Sign out<br>Move the Account Name dropdown menu to Account Summary as shown in Figure 12. See 2.
|  | 2 | 2 | Related to 1 | This is the new position for the Account Name dropdown menu in Account Summary.
|  | 3 | 3 | Related to 1 | Add new icon button to quickly access the Accounts tab.<br><br>_This corresponds to the new `Home` icon button added in 6._
|  | 4 | 4 | `My accounts` should be `My Accounts` | Change `My account` to `My Accounts`.
|  | 5 | 5 | Missing sort feature | Add sort feature as described in Figure 13.
|  | 6 | 6 | Related to 1 | Add new icon button on the selected Account to quickly return to Home screen.<br><br>_This corresponds to the new `Accounts` icon button added in 3._
|  | 7 | 7 | Placing the `Show Wizard` button here is inconsistent with the overall layout, clutters the Home screen and disturbs the Visual Hierarchy of the elements. | Needs redesign. Consider the nature of Harvesting among other factors:<br>- Account specific <br>- Node specific
|  | 8 | 8 | Colour and contrast of the Harvesting icon is inconsistent with similar icons in the same region. | Fix the Harvesting icon colour and contrast.
|  | 9 | 9 | Transactions or Accounts? | Fix issue.
|  | 10 | 10 | The animation on these numbers is distracting and gives the impression that wallet is out of order - it should not run when disconnected from the internet. | It might be more useful to show the timestamp (with timezone) when the key network data were last updated.<br>The timestamp can be shown in the header to the left of the `Console` button.
|  | 11 | 11 | By looking at the Assets list, user has no way of knowing whether it has been filtered without resorting to clicking the menu icon. | Show total assets shown / total assets owned beside “Assets”.<br>Example:<br>Assets (3/10)
|  | 12 | 12 | Improper choice of icon to depict an action to filter the Assets list.Icon contrast is low. | Use a filter icon.<br>Use suitable contrast.
|  | 13 | 13 | The entire Home screen is the Dashboard, not just the Transactions view. | Change `Dashboard` to `Transactions`.
|  | 14 | 14 | The background colour in the table header visually splits the body into 2 sections. | Change the background colour of the table header.<br>UPPERCASE the column names to provide the differentiation.<br><br>From/To (action) —> FROM / TO (ACTION) <br>Amount —> AMOUNT <br>Height —> HEIGHT <br>Hash/Date —> HASH/DATE
|  | 15 | 15 | Some of these icons need to be redesigned. For instance, the icon chosen to represent Namespaces is unsuitable as it is already quite well established as depicting Sales, Discounts, or Promotions. | Establish a common interface inventory for all Symbol platform projects.
|  | 16 | 16 | The sidebar icons buttons are already large. This makes the chosen style of the activated button look too bold and the UI to look busy. | Use subtler styling for the activated buttons on the sidebar.<br>Establish a common interface inventory for all Symbol platform projects.

For further details, please refer to PDF:
[UsabilityInspection-DesktopWallet-Home-Rel-1.0.pdf](https://github.com/nemfoundation/symbol-desktop-wallet/files/4885261/UsabilityInspection-DesktopWallet-Home-Rel-1.0.pdf)

Note: 
There are separate tickets for the usability inspection/analysis of the following:
- Create Profile Screen #451
- Create Profile Screen (Modals/Windows) #452

**Comment by coiki** [comment]
@fullcircle23 Nice to meet you, I'm Alfonso the new Product Manager here at Symbol's wallet. I really liked the work you did here. The wallet has changed since your tickets were created, but I'd like to reach out and show you what we're working on for the future. Are you in the Discord? Thank you for reporting!
