### ISSUE TITLE
The program should display its name

### ISSUE THREAD

**Issue by segfaultxavi** [symbol/desktop-wallet#570]
I guess the name of this program is "Symbol Wallet" or "Symbol Desktop Wallet". It should be shown at the very beginning, in the welcome screen, and at the top of the main UI.
Currently it only shows "Symbol by NEM" in both places.

Both the Explorer and the Faucet do this, the Wallet shouldn't be any different.

Otherwise instructions and screenshots get confusing, plus, in the future, there might be other wallet programs, right?

**Comment by cryptoBeliever** [comment]
@segfaultxavi when you running installed version you have in top bar "Symbol Wallet". Do you think that it's it good enought?

![image](https://user-images.githubusercontent.com/17684281/105891031-6f6ba180-6010-11eb-8409-a9b57a5cb7b6.png)

**Comment by segfaultxavi** [comment]
I guess I'm a romantic but I like proud programs that announce themselves with a big splash screen and then keep the program's icon or logo constantly on screen :)
But this is definitely a matter of taste, so no pressure. Marketing will probably have something to say, though.

**Comment by myxmaster** [comment]
I agree with this. People need a clear name to refer to the app. It is very useful for us as well, when we are trying to help users.

So if the name of this app is "Symbol Desktop Wallet", why don't we put that on the very top left (where it says "Symbol From NEM" now) and put the "Symbol From NEM" to the bottom where it says "Powered by NEM Technology." now (which sounds very generic/meaningless/redundant anyways).

The name should also be visible in Settings -> About.

**Comment by coiki** [comment]
@segfaultxavi @myxmaster We're closing this task to clear the backlog. I agree with the points brought up in this issue, which I appreciate you raised.

Here is a _very early prototype_ of a new wallet where we took your feedback into consideration:
![image](https://user-images.githubusercontent.com/620159/130569921-71fd966e-d043-40a1-9261-e3d38decf44f.png)

For the time being we will keep this wallet as is and work on fixing UX issues and bugs. Thanks! <3
