### ISSUE TITLE
Add private and private test network types

### ISSUE THREAD

**Issue by fboucquez** [symbol/desktop-wallet#752]
The latest alpha SDK adds private and private test networks

https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/dev/src/model/network/NetworkType.ts#L45

We should add those to the wallet, for example, the network type selectors:

![image](https://user-images.githubusercontent.com/5390558/100636393-6dd37500-3310-11eb-953f-15ce252bbfd3.png)

At least:

https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/main/src/views/pages/settings/AboutPage/AboutPage.vue#L38
https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/main/src/core/utils/NetworkTypeHelper.ts#L26

About page should use the NetworkTypeHelper, NetworkTypeHelper could enum the values from SDK's NetworkType

**Comment by cryptoBeliever** [comment]
I have another opinion. For me for public release should be visible only MAINNET and TESTNET. Others can confuse users.

**Comment by coiki** [comment]
Closing due to scope change. cc @fboucquez @cryptoBeliever
