### ISSUE TITLE
Add "ToS" and "Privacy Policy" links to Settings Screen.

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/desktop-wallet#814]
When creating a wallet user can read terms and privacy policy.
After wallet is created there is no way to open it again. I think there should be links somewhere in wallet allowing opening it.

**Comment by AnthonyLaw** [comment]
`Tos` and `Privacy Policy` actually are Vue components.

I don't think that is a good idea to place it under `About` Tab.

![Screenshot 2021-09-02 at 6 29 09 PM](https://user-images.githubusercontent.com/5649156/131829831-051ccb33-ab0d-4264-b90d-c8f66441869d.png)

What do you think if we put it under the bottom?
![Screenshot 2021-09-02 at 6 38 45 PM](https://user-images.githubusercontent.com/5649156/131829869-f61bb06e-3ffc-4a21-9e9d-a1e812495d5e.png)

**Comment by cryptoBeliever** [comment]
Looks good to me :)

**Comment by cryptoBeliever** [comment]
Fixed in dev :+1:
