### ISSUE TITLE
Need to be able to initiate txs for other in Aggregates

### ISSUE THREAD

**Issue by jabo38** [symbol/desktop-wallet#884]
One of the powerful features of aggregates it is that Alice can initiate a tx for Bob's account to do any tx, like send coins, make an alias, and what not. 

Right now that isn't built into the Symbol wallet. This is a feature that is much better than an invoice because now Bob only needs to review the tx, not create it.

**Comment by jabo38** [comment]
Basically, like in this screenshot, I would like to be able to send from another account. 

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/10395907/108123892-271e2d00-706c-11eb-9375-5c371e13ee25.png">

If per the screenshot, I was able to paste in another person's address, that would be great.

**Comment by jabo38** [comment]
The power of this is too, it enables trestles OTC trades in the wallet.  

Basically, I have XYM and somebody else has FOOcoin. I can now send them XYM and they send me FOOcoin in a single transaction. This is essentially a one time use smart contract.  If somebody was to make this on Ethereum, it would take some seriously coding, but for us, it just takes some clicking.

**Comment by jabo38** [comment]
I did a mockup, If this function could be added to the wallet on the UI/UX side, the wallet will now support multiple-party swaps, which is really cool.  

![image](https://user-images.githubusercontent.com/10395907/108231581-854c1e00-7107-11eb-9153-3e9243e21250.png)

**Comment by cryptoBeliever** [comment]
I mentioned this issue in aggregate improvements task (https://github.com/symbol/desktop-wallet/issues/1322)
